import {
  Css3Logo,
  DockerLogo,
  GitHubActionLogo,
  Html5Logo,
  JavascriptLogo,
  MaterialUILogo,
  NextJsLogo,
  NginxLogo,
  ReactLogo,
  ReactQueryLogo,
  ReactRouterLogo,
  SassLogo,
  StorybookLogo,
  StyledComponentsLogo,
  TailwindCssLogo,
  TypescriptLogo,
  ViteLogo,
} from '../../assets/icons';

export const technologies = [
  { name: 'javascript', icon: JavascriptLogo },
  { name: 'typescript', icon: TypescriptLogo },
  { name: 'html5', icon: Html5Logo },
  { name: 'css3', icon: Css3Logo },
  { name: 'react', icon: ReactLogo },
  { name: 'nextjs', icon: NextJsLogo },
  { name: 'react-router', icon: ReactRouterLogo },
  { name: 'react-query', icon: ReactQueryLogo },
  { name: 'tailwindcss', icon: TailwindCssLogo },
  { name: 'sass', icon: SassLogo },
  { name: 'styled-components', icon: StyledComponentsLogo },
  { name: 'material-ui', icon: MaterialUILogo },
  { name: 'docker', icon: DockerLogo },
  { name: 'nginx', icon: NginxLogo },
  { name: 'github-action', icon: GitHubActionLogo },
  { name: 'vite', icon: ViteLogo },
  { name: 'story-book', icon: StorybookLogo },
];
